### ISSUE TITLE
Re-creating branches

### ISSUE THREAD

**Issue by saulrayyy** [DanielKlas/159360132875t#3]
The branch structure might need revision, since we have moved from using a Minutes file to using a single markdown file within master branch. I have also updated the contribution log to be a markdown file, so it might also be good to delete the Minutes, develop and release branches, and to re-build the last two without the extra fluff files.

**Comment by saulrayyy** [comment]
We can discuss this on Friday 24/01/2020 at the meeting if that's okay, since it's a pretty major change to the repository.

**Comment by CJTimmins** [comment]
I've removed the minutes and contribution markdown files from master, release and develop and moved them to their own minutes branch that can be updated independently. This mirrors the setup we have for the code of conduct markdown file.

**Comment by Philip181** [comment]
I think we have a major misunderstanding of the purposes of branches we should discuss on Friday.

**Comment by saulrayyy** [comment]
Discussed, resolved, branches created.
